services:
  vprodb:
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    image: tentinqu/vprodb:latest
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached:latest
    container_name: vprocache01
    ports:
      - "11211:11211"

  vprormq01:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"

  vproapp:
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    image: tentinqu/vproapp:latest
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappadata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
      dockerfile: Dockerfile
    image: tentinqu/vproweb:latest
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappadata: {}